"""Roadmap service - helpers for creating and updating roadmaps."""
import json
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.models.models import Roadmap, Milestone


async def create_roadmap_from_ai(db: AsyncSession, user_id: str, roadmap_data: dict) -> Roadmap:
    """Persist a roadmap generated by the AI service."""
    roadmap = Roadmap(
        id=str(uuid.uuid4()),
        user_id=user_id,
        title=roadmap_data.get("title", "My Learning Roadmap"),
        goal=roadmap_data.get("goal", ""),
        description=roadmap_data.get("description", ""),
        total_months=roadmap_data.get("total_months", 12),
        status="active",
        ai_generated_data=json.dumps(roadmap_data),
    )
    db.add(roadmap)
    await db.flush()

    for m in roadmap_data.get("milestones", []):
        diff_raw = m.get("difficulty", "beginner").lower()
        valid_diffs = {"beginner", "intermediate", "advanced"}
        diff = diff_raw if diff_raw in valid_diffs else "beginner"

        milestone = Milestone(
            id=str(uuid.uuid4()),
            roadmap_id=roadmap.id,
            month_number=m.get("month_number", 1),
            title=m.get("title", ""),
            description=m.get("description"),
            topics=json.dumps(m.get("topics", [])),
            resources=json.dumps(m.get("resources", [])),
            projects=json.dumps(m.get("projects", [])),
            estimated_hours=m.get("estimated_hours"),
            difficulty=diff,
            outcomes=json.dumps(m.get("outcomes", [])),
        )
        db.add(milestone)

    return roadmap


async def recalculate_roadmap_progress(db: AsyncSession, roadmap_id: str) -> float:
    """Recalculate and persist completion percentage."""
    result = await db.execute(
        select(Roadmap)
        .where(Roadmap.id == roadmap_id)
        .options(selectinload(Roadmap.milestones))
    )
    roadmap = result.scalar_one_or_none()
    if not roadmap or not roadmap.milestones:
        return 0.0

    completed = sum(1 for m in roadmap.milestones if m.is_completed)
    pct = round((completed / len(roadmap.milestones)) * 100, 1)
    roadmap.completion_percentage = pct
    return pct
